### PR TITLE
Nesting Solution

### PR DESCRIPTION
**Pull request by VHPaiva**
lement counting in blockquote, to pop the right amount of elements.
Added inline Ids to all elements, turning nesting possible.

### CODE REVIEW

**Comment by christianalfoni** [comment]
Hi @VHPaiva and thanks for the PR!

I am not sure what it solves? Do you have markdown examples of what does not work now and what does work after the PR? :)

**Comment by VHPaiva** [comment]
It is a solution for Issue #18
Blockquote would not suport elements that are not paragraph inside it, as well as popping only one element from the result array, wich would duplicate the content before the blockquote.

`> ## Title`
`> `
`> Item one.`
`> `
`> Item two.`

This would print:

## Title

Item one.

> undefined
> 
> Item one.
>
> Item two.

After the PR, it will print the correct result, and also suppot tables, lists and other blockquotes inside.

**Comment by christianalfoni** [comment]
Aha! I see now, great! Thanks for looking into this :)

**Comment by christianalfoni** [comment]
New version is published!

**Pull request merged**
